using System.Globalization;
using System.Net;
using System.Text;
using Direnix.Core.Findings;
using Direnix.Core.Storage;

namespace Direnix.Core.Reporting;

/// <summary>Dados consolidados para o relatorio exportavel (mesmas fontes do painel).</summary>
public sealed record ReportModel(
    DateTimeOffset GeneratedAt,
    string ProductVersion,
    string PortalUrl,
    string? DomainName,
    string CoverageMode,
    DateTimeOffset? LatestRunCompletedAt,
    int IdentityScore,
    int Tier0Score,
    int ActiveFindings,
    IReadOnlyList<SeverityCount> SeverityBreakdown,
    IReadOnlyList<CategoryCount> CategoryBreakdown,
    IReadOnlyList<FindingRow> TopFindings,
    IReadOnlyList<IndicatorResultRow> Indicators,
    IReadOnlyList<ChangeCount> ChangeSummary24H,
    int NewFindings24H,
    IReadOnlyList<InventoryState> Inventory);

/// <summary>
/// Gera o relatorio HTML autocontido (CSS inline, sem assets externos) e os exports CSV.
/// O HTML e pensado para ser anexado/encaminhado por e-mail e aberto no navegador.
/// </summary>
public static class ReportBuilder
{
    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["pt"] = new()
        {
            ["title"] = "Relatório de identidade",
            ["generatedAt"] = "Gerado em",
            ["domain"] = "Domínio",
            ["noCollection"] = "Nenhuma coleta concluída ainda. Execute uma avaliação para popular este relatório.",
            ["lastCollection"] = "Última coleta",
            ["identityScore"] = "Identity Score",
            ["tier0Score"] = "Score Tier 0",
            ["activeRisks"] = "Riscos ativos",
            ["newRisks24h"] = "Novos riscos (24h)",
            ["bySeverity"] = "Riscos por severidade",
            ["byCategory"] = "Riscos por categoria",
            ["topRisks"] = "Principais riscos",
            ["indicators"] = "Indicadores operacionais",
            ["changes24h"] = "Mudanças nas últimas 24h",
            ["inventory"] = "Inventário",
            ["colSeverity"] = "Severidade",
            ["colCategory"] = "Categoria",
            ["colRisk"] = "Risco",
            ["colObject"] = "Objeto",
            ["colCount"] = "Qtde",
            ["colType"] = "Tipo",
            ["colTotal"] = "Total",
            ["footer"] = "Gerado por Direnix {0} — operação diária de identidade. Portal local: {1}",
            ["Critical"] = "Crítico", ["High"] = "Alto", ["Medium"] = "Médio", ["Low"] = "Baixo", ["Info"] = "Info",
            ["Hygiene"] = "Higiene", ["PrivilegedAccess"] = "Acesso Privilegiado", ["Hardening"] = "Endurecimento",
            ["Infrastructure"] = "Infraestrutura", ["Governance"] = "Governança",
            ["ObjectCreated"] = "Objeto criado", ["ObjectDeleted"] = "Objeto excluído",
            ["MemberAdded"] = "Membro adicionado", ["MemberRemoved"] = "Membro removido",
            ["PrivilegedMemberAdded"] = "Novo membro privilegiado", ["PrivilegedMemberRemoved"] = "Membro privilegiado removido",
            ["AccountEnabled"] = "Conta habilitada", ["AccountDisabled"] = "Conta desabilitada",
            ["DangerousFlagSet"] = "Flag perigosa ativada", ["DangerousFlagCleared"] = "Flag perigosa removida",
            ["AdminCountChanged"] = "adminCount alterado", ["SpnAdded"] = "SPN adicionado",
            ["GpoLinkChanged"] = "Vínculo de GPO alterado", ["AttributeChanged"] = "Atributo alterado"
        },
        ["en"] = new()
        {
            ["title"] = "Identity report",
            ["generatedAt"] = "Generated at",
            ["domain"] = "Domain",
            ["noCollection"] = "No completed collection yet. Run an assessment to populate this report.",
            ["lastCollection"] = "Last collection",
            ["identityScore"] = "Identity Score",
            ["tier0Score"] = "Tier 0 score",
            ["activeRisks"] = "Active risks",
            ["newRisks24h"] = "New risks (24h)",
            ["bySeverity"] = "Risks by severity",
            ["byCategory"] = "Risks by category",
            ["topRisks"] = "Top risks",
            ["indicators"] = "Operational indicators",
            ["changes24h"] = "Changes in the last 24h",
            ["inventory"] = "Inventory",
            ["colSeverity"] = "Severity",
            ["colCategory"] = "Category",
            ["colRisk"] = "Risk",
            ["colObject"] = "Object",
            ["colCount"] = "Count",
            ["colType"] = "Type",
            ["colTotal"] = "Total",
            ["footer"] = "Generated by Direnix {0} — daily identity operations. Local portal: {1}",
            ["Critical"] = "Critical", ["High"] = "High", ["Medium"] = "Medium", ["Low"] = "Low", ["Info"] = "Info",
            ["Hygiene"] = "Hygiene", ["PrivilegedAccess"] = "Privileged Access", ["Hardening"] = "Hardening",
            ["Infrastructure"] = "Infrastructure", ["Governance"] = "Governance",
            ["ObjectCreated"] = "Object created", ["ObjectDeleted"] = "Object deleted",
            ["MemberAdded"] = "Member added", ["MemberRemoved"] = "Member removed",
            ["PrivilegedMemberAdded"] = "New privileged member", ["PrivilegedMemberRemoved"] = "Privileged member removed",
            ["AccountEnabled"] = "Account enabled", ["AccountDisabled"] = "Account disabled",
            ["DangerousFlagSet"] = "Dangerous flag set", ["DangerousFlagCleared"] = "Dangerous flag cleared",
            ["AdminCountChanged"] = "adminCount changed", ["SpnAdded"] = "SPN added",
            ["GpoLinkChanged"] = "GPO link changed", ["AttributeChanged"] = "Attribute changed"
        }
    };

    public static string BuildHtml(ReportModel model, string lang)
    {
        var l = Strings.ContainsKey(lang) ? lang : "pt";
        string T(string key) => Strings[l].TryGetValue(key, out var v) ? v : key;
        string E(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);
        string Date(DateTimeOffset? value) => value is null
            ? "—"
            : value.Value.ToLocalTime().ToString(l == "pt" ? "dd/MM/yyyy HH:mm" : "yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture);

        var hasRun = model.LatestRunCompletedAt is not null;
        var scoreColor = model.IdentityScore >= 80 ? "#1a7f4b" : model.IdentityScore >= 60 ? "#b26a00" : "#b3261e";
        var sb = new StringBuilder(32 * 1024);

        sb.Append("<!doctype html><html lang=\"").Append(l == "pt" ? "pt-BR" : "en").Append("\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append("<title>Direnix — ").Append(E(T("title"))).Append("</title><style>");
        sb.Append("body{font-family:'Segoe UI',Arial,sans-serif;color:#1c2430;background:#f4f6f9;margin:0;padding:24px}");
        sb.Append(".wrap{max-width:860px;margin:0 auto;background:#fff;border:1px solid #dde3ea;border-radius:10px;padding:28px}");
        sb.Append("h1{font-size:22px;margin:0 0 2px}h2{font-size:15px;margin:26px 0 8px;border-bottom:1px solid #e4e9ef;padding-bottom:5px}");
        sb.Append(".muted{color:#5c6a7a;font-size:12px}.brand{display:inline-block;background:#14324f;color:#fff;border-radius:7px;padding:6px 10px;font-weight:700;margin-right:10px}");
        sb.Append("table{border-collapse:collapse;width:100%;font-size:13px}th{text-align:left;color:#5c6a7a;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.04em}");
        sb.Append("th,td{padding:6px 8px;border-bottom:1px solid #eef1f5}td.num{text-align:right;font-variant-numeric:tabular-nums}");
        sb.Append(".cards{display:flex;flex-wrap:wrap;gap:12px;margin:18px 0}.card{flex:1 1 150px;border:1px solid #dde3ea;border-radius:8px;padding:12px 14px}");
        sb.Append(".card .v{font-size:26px;font-weight:700}.card .k{font-size:11px;color:#5c6a7a;text-transform:uppercase;letter-spacing:.04em}");
        sb.Append(".sev{display:inline-block;border-radius:4px;padding:1px 7px;font-size:11px;font-weight:600;color:#fff}");
        sb.Append(".sev-Critical{background:#b3261e}.sev-High{background:#d1495b}.sev-Medium{background:#b26a00}.sev-Low{background:#3b6ea5}.sev-Info{background:#5c6a7a}");
        sb.Append(".empty{color:#5c6a7a;font-size:13px;padding:14px;border:1px dashed #ccd4dd;border-radius:8px;text-align:center}");
        sb.Append("footer{margin-top:26px;font-size:11px;color:#5c6a7a;border-top:1px solid #e4e9ef;padding-top:10px}");
        sb.Append("</style></head><body><div class=\"wrap\">");

        sb.Append("<div><span class=\"brand\">DX</span><span style=\"font-size:19px;font-weight:700\">Direnix</span></div>");
        sb.Append("<h1>").Append(E(T("title"))).Append("</h1>");
        sb.Append("<p class=\"muted\">").Append(E(T("generatedAt"))).Append(": ").Append(Date(model.GeneratedAt));
        if (!string.IsNullOrWhiteSpace(model.DomainName))
        {
            sb.Append(" · ").Append(E(T("domain"))).Append(": <strong>").Append(E(model.DomainName)).Append("</strong>");
        }
        sb.Append(" · ").Append(E(T("lastCollection"))).Append(": ").Append(Date(model.LatestRunCompletedAt)).Append("</p>");

        if (!hasRun)
        {
            sb.Append("<div class=\"empty\">").Append(E(T("noCollection"))).Append("</div>");
        }
        else
        {
            sb.Append("<div class=\"cards\">");
            sb.Append("<div class=\"card\"><div class=\"v\" style=\"color:").Append(scoreColor).Append("\">").Append(model.IdentityScore)
              .Append("</div><div class=\"k\">").Append(E(T("identityScore"))).Append("</div></div>");
            sb.Append("<div class=\"card\"><div class=\"v\">").Append(model.Tier0Score).Append("</div><div class=\"k\">").Append(E(T("tier0Score"))).Append("</div></div>");
            sb.Append("<div class=\"card\"><div class=\"v\">").Append(model.ActiveFindings).Append("</div><div class=\"k\">").Append(E(T("activeRisks"))).Append("</div></div>");
            sb.Append("<div class=\"card\"><div class=\"v\">").Append(model.NewFindings24H).Append("</div><div class=\"k\">").Append(E(T("newRisks24h"))).Append("</div></div>");
            sb.Append("</div>");

            if (model.ChangeSummary24H.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("changes24h"))).Append("</h2><table><tbody>");
                foreach (var change in model.ChangeSummary24H)
                {
                    sb.Append("<tr><td>").Append(E(T(change.ChangeType))).Append("</td><td class=\"num\">").Append(change.Count).Append("</td></tr>");
                }
                sb.Append("</tbody></table>");
            }

            if (model.Indicators.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("indicators"))).Append("</h2><table><tbody>");
                foreach (var indicator in model.Indicators)
                {
                    sb.Append("<tr><td>").Append(E(indicator.Title)).Append("</td><td class=\"num\"><strong>").Append(indicator.Count).Append("</strong></td></tr>");
                }
                sb.Append("</tbody></table>");
            }

            if (model.SeverityBreakdown.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("bySeverity"))).Append("</h2><table><tbody>");
                foreach (var severity in model.SeverityBreakdown)
                {
                    sb.Append("<tr><td><span class=\"sev sev-").Append(severity.Severity).Append("\">").Append(E(T(severity.Severity.ToString())))
                      .Append("</span></td><td class=\"num\">").Append(severity.Count).Append("</td></tr>");
                }
                sb.Append("</tbody></table>");
            }

            if (model.CategoryBreakdown.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("byCategory"))).Append("</h2><table><tbody>");
                foreach (var category in model.CategoryBreakdown)
                {
                    sb.Append("<tr><td>").Append(E(T(category.Category.ToString()))).Append("</td><td class=\"num\">").Append(category.Count).Append("</td></tr>");
                }
                sb.Append("</tbody></table>");
            }

            if (model.TopFindings.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("topRisks"))).Append("</h2><table><thead><tr><th>").Append(E(T("colSeverity")))
                  .Append("</th><th>").Append(E(T("colCategory"))).Append("</th><th>").Append(E(T("colRisk")))
                  .Append("</th><th>").Append(E(T("colObject"))).Append("</th></tr></thead><tbody>");
                foreach (var finding in model.TopFindings)
                {
                    sb.Append("<tr><td><span class=\"sev sev-").Append(finding.Severity).Append("\">").Append(E(T(finding.Severity.ToString())))
                      .Append("</span></td><td>").Append(E(T(finding.Category.ToString())))
                      .Append("</td><td>").Append(E(finding.Title))
                      .Append("</td><td>").Append(E(finding.ObjectDisplay)).Append("</td></tr>");
                }
                sb.Append("</tbody></table>");
            }

            if (model.Inventory.Count > 0)
            {
                sb.Append("<h2>").Append(E(T("inventory"))).Append("</h2><table><thead><tr><th>").Append(E(T("colType")))
                  .Append("</th><th style=\"text-align:right\">").Append(E(T("colTotal"))).Append("</th></tr></thead><tbody>");
                foreach (var item in model.Inventory)
                {
                    sb.Append("<tr><td>").Append(E(item.ObjectType)).Append("</td><td class=\"num\">").Append(item.TotalCount).Append("</td></tr>");
                }
                sb.Append("</tbody></table>");
            }
        }

        sb.Append("<footer>").Append(string.Format(CultureInfo.InvariantCulture, E(T("footer")), E(model.ProductVersion), E(model.PortalUrl))).Append("</footer>");
        sb.Append("</div></body></html>");
        return sb.ToString();
    }

    /// <summary>CSV de riscos. Primeira linha "sep=," garante colunas corretas no Excel em qualquer locale.</summary>
    public static string BuildFindingsCsv(IReadOnlyList<FindingRow> rows, string lang)
    {
        var l = Strings.ContainsKey(lang) ? lang : "pt";
        string T(string key) => Strings[l].TryGetValue(key, out var v) ? v : key;

        var sb = new StringBuilder();
        sb.AppendLine("sep=,");
        sb.AppendLine(string.Join(',', new[]
        {
            T("colSeverity"), T("colCategory"), "RuleId", T("colRisk"), T("colObject"),
            "Score", "Status", "FirstSeen", "LastSeen"
        }.Select(CsvField)));
        foreach (var row in rows)
        {
            sb.AppendLine(string.Join(',', new[]
            {
                T(row.Severity.ToString()), T(row.Category.ToString()), row.RuleId, row.Title, row.ObjectDisplay,
                row.BusinessRiskScore.ToString(CultureInfo.InvariantCulture), row.Status.ToString(),
                row.FirstSeen.ToLocalTime().ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture),
                row.LastSeen.ToLocalTime().ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)
            }.Select(CsvField)));
        }

        return sb.ToString();
    }

    /// <summary>CSV do inventario atual por tipo de objeto.</summary>
    public static string BuildInventoryCsv(IReadOnlyList<InventoryState> inventory, string lang)
    {
        var l = Strings.ContainsKey(lang) ? lang : "pt";
        string T(string key) => Strings[l].TryGetValue(key, out var v) ? v : key;

        var sb = new StringBuilder();
        sb.AppendLine("sep=,");
        sb.AppendLine(string.Join(',', new[] { T("colType"), T("colTotal"), "LastObservedAt" }.Select(CsvField)));
        foreach (var item in inventory)
        {
            sb.AppendLine(string.Join(',', new[]
            {
                item.ObjectType,
                item.TotalCount.ToString(CultureInfo.InvariantCulture),
                item.LastObservedAt?.ToLocalTime().ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) ?? string.Empty
            }.Select(CsvField)));
        }

        return sb.ToString();
    }

    private static string CsvField(string? value)
    {
        var text = value ?? string.Empty;
        if (text.Contains(',') || text.Contains('"') || text.Contains('\n') || text.Contains('\r'))
        {
            return '"' + text.Replace("\"", "\"\"") + '"';
        }

        return text;
    }
}
